name: Publish to npm

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org

      - name: Setup esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: Bundle
        run: |
          exports=$(jq '.exports' package.json -r)
          ./esbuild $(basename $exports .js).ts --outfile=$exports

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
